version: '3'

services:
  practicadb:
    image: postgres
    container_name: x
    restart: always
    environment:
      POSTGRES_USER=x
      POSTGRES_PASSWORD=x
      POSTGRES_DB=x
    ports:
       5432:5432
    volumes:
      dbdata:/var/lib/postgresql/data
volumes:
  dbdata: